# Generated by Django 3.1.4 on 2020-12-06 02:18

from django.db import migrations, models
import django.db.models.deletion
import functools
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmae', models.CharField(max_length=200)),
                ('data', models.JSONField(default=dict)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notion.collection')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('icon', models.CharField(max_length=200)),
                ('title', models.TextField()),
                ('wide', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notion.page')),
            ],
        ),
        migrations.CreateModel(
            name='LayoutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notion.page')),
            ],
            bases=('notion.page',),
        ),
        migrations.CreateModel(
            name='CollectionView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('TALBE', 'Table'), ('BOARD', 'Board'), ('TIMELINE', 'Timeline'), ('LIST', 'List'), ('CALENDAR', 'Calendar'), ('GALLERY', 'Gallery')], max_length=50)),
                ('data', models.JSONField(default=dict)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notion.collection')),
            ],
        ),
        migrations.CreateModel(
            name='PageProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=functools.partial(dict, *(), **{'value': ''}))),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notion.collectionproperty')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notion.layoutpage')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('TEXT', 'Text'), ('LINK', 'Link'), ('H1', 'Heading 1'), ('H2', 'Heading 1'), ('H3', 'Heading 1'), ('BULLETED_LIST', 'Bulleted list'), ('NUMBERED_LIST', 'Numbered list'), ('TOGGLE', 'Toggle'), ('QUOTE', 'Quote'), ('DIVIDER', 'Divider'), ('CALL_OUT', 'Call Out'), ('EMBED', 'Embed')], max_length=50)),
                ('data', models.JSONField(null=True)),
                ('column', models.IntegerField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notion.layoutpage')),
            ],
        ),
    ]
