# Generated by Django 3.1.4 on 2020-12-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='column',
            new_name='col',
        ),
        migrations.AddField(
            model_name='block',
            name='row',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='page',
            name='icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.TextField(default='Untitled'),
        ),
    ]
