# Generated by Django 3.1.4 on 2020-12-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0002_auto_20201206_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionproperty',
            name='nmae',
        ),
        migrations.AddField(
            model_name='collectionproperty',
            name='name',
            field=models.CharField(blank=True, default='Column', max_length=200),
        ),
        migrations.AlterField(
            model_name='block',
            name='col',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='collectionview',
            name='type',
            field=models.CharField(choices=[('TALBE', 'Table'), ('BOARD', 'Board'), ('TIMELINE', 'Timeline'), ('LIST', 'List'), ('CALENDAR', 'Calendar'), ('GALLERY', 'Gallery')], default='TALBE', max_length=50),
        ),
    ]
